-- ============================================================
-- Korakuen Management System — Fix views security invoker
-- Migration: 007 (supersedes migration 004)
-- Date: 2026-03-01
-- Recreates all views with security_invoker = on
--
-- Note: Migration 006 was skipped — this migration was
-- originally numbered 006 but was regenerated as 007.
--
-- SOURCE OF TRUTH: supabase/views/*.sql
-- This migration was generated by combining the individual
-- view files. To update views, edit the source files in
-- supabase/views/ and create a new migration.
-- ============================================================

-- View: v_cost_totals
-- Purpose: Derives subtotal, igv_amount, detraccion_amount, total per cost from cost_items
-- Source tables: costs, cost_items
-- Used by: v_cost_balances, v_ap_calendar, v_project_pl, v_company_pl, v_entity_transactions, v_partner_ledger

CREATE OR REPLACE VIEW v_cost_totals
WITH (security_invoker = on)
AS
WITH item_sums AS (
  SELECT
    c.id                  AS cost_id,
    c.project_id,
    c.valuation_id,
    c.bank_account_id,
    c.entity_id,
    c.quote_id,
    c.purchase_order_id,
    c.cost_type,
    c.date,
    c.title,
    c.igv_rate,
    c.detraccion_rate,
    c.currency,
    c.exchange_rate,
    c.comprobante_type,
    c.comprobante_number,
    c.document_ref,
    c.due_date,
    c.notes,
    COALESCE(SUM(ci.subtotal), 0) AS subtotal
  FROM costs c
  LEFT JOIN cost_items ci ON ci.cost_id = c.id
  GROUP BY
    c.id,
    c.project_id,
    c.valuation_id,
    c.bank_account_id,
    c.entity_id,
    c.quote_id,
    c.purchase_order_id,
    c.cost_type,
    c.date,
    c.title,
    c.igv_rate,
    c.detraccion_rate,
    c.currency,
    c.exchange_rate,
    c.comprobante_type,
    c.comprobante_number,
    c.document_ref,
    c.due_date,
    c.notes
),
with_igv AS (
  SELECT
    *,
    ROUND(subtotal * (igv_rate / 100), 2) AS igv_amount
  FROM item_sums
)
SELECT
  cost_id,
  project_id,
  valuation_id,
  bank_account_id,
  entity_id,
  quote_id,
  purchase_order_id,
  cost_type,
  date,
  title,
  igv_rate,
  detraccion_rate,
  currency,
  exchange_rate,
  comprobante_type,
  comprobante_number,
  document_ref,
  due_date,
  notes,
  subtotal,
  igv_amount,
  subtotal + igv_amount                                                    AS total,
  ROUND((subtotal + igv_amount) * COALESCE(detraccion_rate, 0) / 100, 2)  AS detraccion_amount
FROM with_igv;


-- View: v_cost_balances
-- Purpose: Shows amount_paid, outstanding balance, and payment_status per cost
-- Source tables: v_cost_totals, payments
-- Used by: v_ap_calendar, cost detail pages, payment tracking

CREATE OR REPLACE VIEW v_cost_balances
WITH (security_invoker = on)
AS
SELECT
  ct.cost_id,
  ct.project_id,
  ct.entity_id,
  ct.bank_account_id,
  ct.cost_type,
  ct.date,
  ct.title,
  ct.currency,
  ct.due_date,
  ct.document_ref,
  ct.subtotal,
  ct.igv_amount,
  ct.total,
  ct.detraccion_amount,
  COALESCE(SUM(p.amount), 0) AS amount_paid,
  ct.total - COALESCE(SUM(p.amount), 0) AS outstanding,
  CASE
    WHEN COALESCE(SUM(p.amount), 0) = 0 THEN 'pending'
    WHEN COALESCE(SUM(p.amount), 0) >= ct.total THEN 'paid'
    ELSE 'partial'
  END AS payment_status
FROM v_cost_totals ct
LEFT JOIN payments p
  ON p.related_id = ct.cost_id
  AND p.related_to = 'cost'
GROUP BY
  ct.cost_id,
  ct.project_id,
  ct.entity_id,
  ct.bank_account_id,
  ct.cost_type,
  ct.date,
  ct.title,
  ct.currency,
  ct.due_date,
  ct.document_ref,
  ct.subtotal,
  ct.igv_amount,
  ct.total,
  ct.detraccion_amount;


-- View: v_ar_balances
-- Purpose: Derives igv_amount, gross_total, detraccion, retencion, net_receivable,
--          amount_paid, outstanding, and payment_status per AR invoice
-- Source tables: ar_invoices, payments
-- Used by: v_settlement_dashboard, AR detail pages, project P&L, company P&L

CREATE OR REPLACE VIEW v_ar_balances
WITH (security_invoker = on)
AS
WITH ar_base AS (
  SELECT
    ar.id                 AS ar_invoice_id,
    ar.project_id,
    ar.valuation_id,
    ar.bank_account_id,
    ar.entity_id,
    ar.partner_company_id,
    ar.invoice_number,
    ar.comprobante_type,
    ar.invoice_date,
    ar.due_date,
    ar.subtotal,
    ar.igv_rate,
    ar.detraccion_rate,
    ar.retencion_applicable,
    ar.retencion_rate,
    ar.currency,
    ar.exchange_rate,
    ar.document_ref,
    ar.is_internal_settlement,
    ar.notes,
    ROUND(ar.subtotal * (ar.igv_rate / 100), 2) AS igv_amount
  FROM ar_invoices ar
),
ar_computed AS (
  SELECT
    ab.*,
    ab.subtotal + ab.igv_amount AS gross_total,
    ROUND(
      (ab.subtotal + ab.igv_amount) * COALESCE(ab.detraccion_rate, 0) / 100, 2
    )                           AS detraccion_amount,
    ROUND(
      CASE
        WHEN ab.retencion_applicable
          THEN (ab.subtotal + ab.igv_amount) * COALESCE(ab.retencion_rate, 0) / 100
        ELSE 0
      END, 2
    )                           AS retencion_amount
  FROM ar_base ab
)
SELECT
  ac.ar_invoice_id,
  ac.project_id,
  ac.valuation_id,
  ac.bank_account_id,
  ac.entity_id,
  ac.partner_company_id,
  ac.invoice_number,
  ac.comprobante_type,
  ac.invoice_date,
  ac.due_date,
  ac.subtotal,
  ac.igv_rate,
  ac.detraccion_rate,
  ac.retencion_applicable,
  ac.retencion_rate,
  ac.currency,
  ac.exchange_rate,
  ac.document_ref,
  ac.is_internal_settlement,
  ac.notes,
  ac.igv_amount,
  ac.gross_total,
  ac.detraccion_amount,
  ac.retencion_amount,
  ac.gross_total - ac.detraccion_amount - ac.retencion_amount AS net_receivable,
  COALESCE(SUM(p.amount), 0) AS amount_paid,
  ac.gross_total - COALESCE(SUM(p.amount), 0) AS outstanding,
  CASE
    WHEN COALESCE(SUM(p.amount), 0) = 0 THEN 'pending'
    WHEN COALESCE(SUM(p.amount), 0) >= ac.gross_total THEN 'paid'
    ELSE 'partial'
  END AS payment_status
FROM ar_computed ac
LEFT JOIN payments p
  ON p.related_id = ac.ar_invoice_id
  AND p.related_to = 'ar_invoice'
GROUP BY
  ac.ar_invoice_id,
  ac.project_id,
  ac.valuation_id,
  ac.bank_account_id,
  ac.entity_id,
  ac.partner_company_id,
  ac.invoice_number,
  ac.comprobante_type,
  ac.invoice_date,
  ac.due_date,
  ac.subtotal,
  ac.igv_rate,
  ac.detraccion_rate,
  ac.retencion_applicable,
  ac.retencion_rate,
  ac.currency,
  ac.exchange_rate,
  ac.document_ref,
  ac.is_internal_settlement,
  ac.notes,
  ac.igv_amount,
  ac.gross_total,
  ac.detraccion_amount,
  ac.retencion_amount;


-- View: v_ap_calendar
-- Purpose: Shows unpaid and partially paid costs sorted by due date with days remaining.
--          Feeds the Accounts Payable payment calendar on the website.
--          Includes both project_cost and sga cost types — all payment obligations are relevant.
-- Source tables: v_cost_balances, projects, entities
-- Used by: AP calendar page, payment planning dashboard

CREATE OR REPLACE VIEW v_ap_calendar
WITH (security_invoker = on)
AS
SELECT
  cb.cost_id,
  cb.project_id,
  p.project_code,
  p.name              AS project_name,
  cb.entity_id,
  COALESCE(e.common_name, e.legal_name) AS entity_name,
  cb.cost_type,
  cb.date,
  cb.title,
  cb.currency,
  cb.document_ref,
  cb.due_date,
  (cb.due_date - CURRENT_DATE) AS days_remaining,
  cb.subtotal,
  cb.igv_amount,
  cb.total,
  cb.detraccion_amount,
  cb.amount_paid,
  cb.outstanding,
  cb.payment_status
FROM v_cost_balances cb
LEFT JOIN projects p ON p.id = cb.project_id AND p.is_active = true
LEFT JOIN entities e ON e.id = cb.entity_id AND e.is_active = true
WHERE cb.due_date IS NOT NULL
  AND cb.payment_status IN ('pending', 'partial')
ORDER BY cb.due_date ASC;


-- View: v_partner_ledger
-- Purpose: Shows each partner's financial contribution per project, calculates
--          proportional ownership percentages, and income distribution.
-- Source tables: costs, bank_accounts, partner_companies, projects, v_cost_totals, ar_invoices, payments
-- Used by: Partner ledger page, settlement calculations, partner dashboard

CREATE OR REPLACE VIEW v_partner_ledger
WITH (security_invoker = on)
AS
WITH partner_costs AS (
  -- Each partner's total cost contribution per project per currency
  SELECT
    ct.project_id,
    ba.partner_company_id,
    ct.currency,
    -- subtotal is pre-IGV (net amount before tax)
    COALESCE(SUM(ct.subtotal), 0) AS contribution_amount
  FROM v_cost_totals ct
  JOIN bank_accounts ba ON ba.id = ct.bank_account_id
  WHERE ct.project_id IS NOT NULL
  GROUP BY ct.project_id, ba.partner_company_id, ct.currency
),
project_totals AS (
  -- Total costs per project per currency (for percentage calculation)
  SELECT
    project_id,
    currency,
    SUM(contribution_amount) AS total_project_costs
  FROM partner_costs
  GROUP BY project_id, currency
),
project_income AS (
  -- Total AR income invoiced per project per currency
  SELECT
    ar.project_id,
    ar.currency,
    -- subtotal is pre-IGV (net amount before tax)
    COALESCE(SUM(ar.subtotal), 0) AS total_income
  FROM ar_invoices ar
  GROUP BY ar.project_id, ar.currency
)
SELECT
  pc.project_id,
  p.project_code,
  p.name                AS project_name,
  pc.partner_company_id,
  pco.name              AS partner_name,
  pc.currency,
  pc.contribution_amount,
  CASE
    WHEN pt.total_project_costs > 0
      THEN ROUND((pc.contribution_amount / pt.total_project_costs) * 100, 2)
    ELSE 0
  END                   AS contribution_pct,
  COALESCE(pi.total_income, 0) AS project_income,
  CASE
    WHEN pt.total_project_costs > 0
      THEN ROUND(
        COALESCE(pi.total_income, 0)
        * (pc.contribution_amount / pt.total_project_costs), 2
      )
    ELSE 0
  END                   AS income_share
FROM partner_costs pc
-- No is_active filter on projects/partner_companies: financial history must remain
-- visible even after deactivation. Filtering handled at the application layer.
JOIN projects p         ON p.id = pc.project_id
JOIN partner_companies pco ON pco.id = pc.partner_company_id
JOIN project_totals pt  ON pt.project_id = pc.project_id
                       AND pt.currency = pc.currency
LEFT JOIN project_income pi ON pi.project_id = pc.project_id
                           AND pi.currency = pc.currency
ORDER BY p.project_code, pco.name;


-- View: v_entity_transactions
-- Purpose: Unified view of all transactions (costs and AR invoices) per entity,
--          enabling a complete transaction history for any entity across projects.
-- Source tables: v_cost_totals, ar_invoices, entities, projects
-- Used by: Entity detail page, entity transaction history

CREATE OR REPLACE VIEW v_entity_transactions
WITH (security_invoker = on)
AS

-- Costs (expenses associated with an entity)
-- No is_active filter on entities/projects: financial history must remain visible
-- even after deactivation. Filtering handled at the application layer.
SELECT
  ct.entity_id,
  e.legal_name          AS entity_name,
  ct.project_id,
  p.project_code,
  p.name                AS project_name,
  'cost'                AS transaction_type,
  ct.date,
  ct.title,
  NULL                  AS invoice_number,
  ct.currency,
  ct.subtotal           AS amount,
  ct.total              AS total_with_igv,
  ct.document_ref,
  ct.cost_id            AS transaction_id
FROM v_cost_totals ct
JOIN entities e ON e.id = ct.entity_id
LEFT JOIN projects p ON p.id = ct.project_id
WHERE ct.entity_id IS NOT NULL

UNION ALL

-- AR Invoices (income from an entity)
SELECT
  ar.entity_id,
  e.legal_name          AS entity_name,
  ar.project_id,
  p.project_code,
  p.name                AS project_name,
  'ar_invoice'          AS transaction_type,
  ar.invoice_date       AS date,
  COALESCE(ar.notes, 'Invoice ' || ar.invoice_number) AS title,
  ar.invoice_number,
  ar.currency,
  ar.subtotal           AS amount,
  ROUND(ar.subtotal + ar.subtotal * (ar.igv_rate / 100), 2) AS total_with_igv,
  ar.document_ref,
  ar.id                 AS transaction_id
FROM ar_invoices ar
JOIN entities e ON e.id = ar.entity_id
LEFT JOIN projects p ON p.id = ar.project_id

ORDER BY date DESC;


-- View: v_bank_balances
-- Purpose: Shows the calculated balance per bank account based on all payment movements.
--          Inbound payments add to balance, outbound payments subtract.
-- Source tables: payments, bank_accounts, partner_companies
-- Used by: Bank account dashboard, treasury overview

CREATE OR REPLACE VIEW v_bank_balances
WITH (security_invoker = on)
AS
SELECT
  ba.id                 AS bank_account_id,
  ba.partner_company_id,
  pc.name               AS partner_name,
  ba.bank_name,
  ba.account_number_last4,
  ba.account_type,
  ba.currency,
  ba.is_detraccion_account,
  COALESCE(
    SUM(
      CASE
        WHEN p.direction = 'inbound' THEN p.amount
        ELSE -p.amount
      END
    ), 0
  )                     AS balance,
  COUNT(p.id)           AS transaction_count
FROM bank_accounts ba
JOIN partner_companies pc ON pc.id = ba.partner_company_id AND pc.is_active = true
LEFT JOIN payments p ON p.bank_account_id = ba.id
WHERE ba.is_active = true
GROUP BY
  ba.id,
  ba.partner_company_id,
  pc.name,
  ba.bank_name,
  ba.account_number_last4,
  ba.account_type,
  ba.currency,
  ba.is_detraccion_account;


-- View: v_project_pl
-- Purpose: Profit and loss per project. Shows income (AR subtotals), project costs
--          (cost subtotals where cost_type = 'project_cost'), and gross profit.
--          Grouped by currency — never mixes currencies.
-- Source tables: ar_invoices, v_cost_totals, projects
-- Used by: Project dashboard, project detail page, financial reports

CREATE OR REPLACE VIEW v_project_pl
WITH (security_invoker = on)
AS
WITH project_income AS (
  SELECT
    ar.project_id,
    ar.currency,
    COALESCE(SUM(ar.subtotal), 0) AS total_income
  FROM ar_invoices ar
  GROUP BY ar.project_id, ar.currency
),
project_costs AS (
  SELECT
    ct.project_id,
    ct.currency,
    COALESCE(SUM(ct.subtotal), 0) AS total_costs
  FROM v_cost_totals ct
  WHERE ct.cost_type = 'project_cost'
    AND ct.project_id IS NOT NULL
  GROUP BY ct.project_id, ct.currency
),
-- Collect all project+currency combinations from both income and costs
all_project_currencies AS (
  SELECT project_id, currency FROM project_income
  UNION
  SELECT project_id, currency FROM project_costs
)
SELECT
  p.id                  AS project_id,
  p.project_code,
  p.name                AS project_name,
  p.status              AS project_status,
  apc.currency,
  COALESCE(pi.total_income, 0)       AS total_income,
  COALESCE(pc.total_costs, 0)        AS total_costs,
  COALESCE(pi.total_income, 0)
    - COALESCE(pc.total_costs, 0)    AS gross_profit,
  CASE
    WHEN COALESCE(pi.total_income, 0) > 0
      THEN ROUND(
        (COALESCE(pi.total_income, 0) - COALESCE(pc.total_costs, 0))
        / COALESCE(pi.total_income, 0) * 100, 2
      )
    ELSE 0
  END                   AS gross_margin_pct
FROM all_project_currencies apc
-- No is_active filter: financial history must remain visible even after project
-- deactivation. Filtering handled at the application layer.
JOIN projects p         ON p.id = apc.project_id
LEFT JOIN project_income pi ON pi.project_id = apc.project_id
                           AND pi.currency = apc.currency
LEFT JOIN project_costs pc  ON pc.project_id = apc.project_id
                           AND pc.currency = apc.currency
ORDER BY p.project_code, apc.currency;


-- View: v_company_pl
-- Purpose: Consolidated company-level profit and loss.
--          Total AR income across all projects, total project costs, total SG&A,
--          and net profit. Grouped by currency — never mixes currencies.
-- Source tables: ar_invoices, v_cost_totals
-- Used by: Company dashboard, financial summary page

CREATE OR REPLACE VIEW v_company_pl
WITH (security_invoker = on)
AS
WITH total_income AS (
  SELECT
    ar.currency,
    COALESCE(SUM(ar.subtotal), 0) AS total_income
  FROM ar_invoices ar
  GROUP BY ar.currency
),
total_project_costs AS (
  SELECT
    ct.currency,
    COALESCE(SUM(ct.subtotal), 0) AS total_project_costs
  FROM v_cost_totals ct
  WHERE ct.cost_type = 'project_cost'
  GROUP BY ct.currency
),
total_sga AS (
  SELECT
    ct.currency,
    COALESCE(SUM(ct.subtotal), 0) AS total_sga
  FROM v_cost_totals ct
  WHERE ct.cost_type = 'sga'
  GROUP BY ct.currency
),
-- Collect all currencies present in any of the three sources
all_currencies AS (
  SELECT currency FROM total_income
  UNION
  SELECT currency FROM total_project_costs
  UNION
  SELECT currency FROM total_sga
)
SELECT
  ac.currency,
  COALESCE(ti.total_income, 0)          AS total_income,
  COALESCE(tpc.total_project_costs, 0)  AS total_project_costs,
  COALESCE(ti.total_income, 0)
    - COALESCE(tpc.total_project_costs, 0) AS gross_profit,
  COALESCE(ts.total_sga, 0)            AS total_sga,
  COALESCE(ti.total_income, 0)
    - COALESCE(tpc.total_project_costs, 0)
    - COALESCE(ts.total_sga, 0)         AS net_profit,
  CASE
    WHEN COALESCE(ti.total_income, 0) > 0
      THEN ROUND(
        (COALESCE(ti.total_income, 0)
          - COALESCE(tpc.total_project_costs, 0)
          - COALESCE(ts.total_sga, 0))
        / COALESCE(ti.total_income, 0) * 100, 2
      )
    ELSE 0
  END                                   AS net_margin_pct
FROM all_currencies ac
LEFT JOIN total_income ti          ON ti.currency = ac.currency
LEFT JOIN total_project_costs tpc  ON tpc.currency = ac.currency
LEFT JOIN total_sga ts             ON ts.currency = ac.currency
ORDER BY ac.currency;


-- View: v_settlement_dashboard
-- Purpose: Shows all internal settlement invoices between partner companies,
--          including computed amounts and payment status.
-- Source tables: v_ar_balances, projects, partner_companies, entities
-- Used by: Partner settlement dashboard, partner reconciliation page

CREATE OR REPLACE VIEW v_settlement_dashboard
WITH (security_invoker = on)
AS
SELECT
  ab.ar_invoice_id,
  ab.project_id,
  p.project_code,
  p.name                    AS project_name,
  ab.partner_company_id,
  pc.name                   AS issuing_partner_name,
  ab.entity_id,
  COALESCE(e.common_name, e.legal_name) AS receiving_entity_name,
  ab.invoice_number,
  ab.invoice_date,
  ab.due_date,
  ab.currency,
  ab.subtotal,
  ab.igv_amount,
  ab.gross_total,
  ab.detraccion_amount,
  ab.retencion_amount,
  ab.net_receivable,
  ab.amount_paid,
  ab.outstanding,
  ab.payment_status,
  ab.document_ref,
  ab.notes
FROM v_ar_balances ab
JOIN projects p             ON p.id = ab.project_id AND p.is_active = true
JOIN partner_companies pc   ON pc.id = ab.partner_company_id AND pc.is_active = true
JOIN entities e             ON e.id = ab.entity_id AND e.is_active = true
WHERE ab.is_internal_settlement = true
ORDER BY ab.invoice_date DESC;


-- View: v_retencion_dashboard
-- Purpose: Tracks AR invoices where retencion is applicable, showing verification status
--          and days since invoice to highlight aged unverified retenciones
-- Source tables: ar_invoices, projects, entities
-- Used by: Retencion dashboard page, retencion verification workflow

CREATE OR REPLACE VIEW v_retencion_dashboard
WITH (security_invoker = on)
AS
WITH ar_base AS (
  SELECT
    ar.id                 AS ar_invoice_id,
    ar.project_id,
    ar.entity_id,
    ar.invoice_number,
    ar.invoice_date,
    ar.due_date,
    ar.subtotal,
    ar.igv_rate,
    ar.retencion_rate,
    ar.currency,
    ar.retencion_verified,
    ROUND(ar.subtotal * (ar.igv_rate / 100), 2) AS igv_amount
  FROM ar_invoices ar
  WHERE ar.retencion_applicable = true
),
ar_with_totals AS (
  SELECT
    ab.*,
    ab.subtotal + ab.igv_amount AS gross_total,
    ROUND(
      (ab.subtotal + ab.igv_amount) * COALESCE(ab.retencion_rate, 0) / 100, 2
    ) AS retencion_amount
  FROM ar_base ab
)
SELECT
  awt.ar_invoice_id,
  p.project_code,
  e.legal_name          AS client_name,
  awt.invoice_number,
  awt.invoice_date,
  awt.due_date,
  awt.gross_total,
  awt.retencion_amount,
  awt.currency,
  awt.retencion_verified,
  (CURRENT_DATE - awt.invoice_date) AS days_since_invoice
FROM ar_with_totals awt
JOIN projects p ON p.id = awt.project_id AND p.is_active = true
JOIN entities e ON e.id = awt.entity_id AND e.is_active = true
ORDER BY
  awt.retencion_verified ASC,
  (CURRENT_DATE - awt.invoice_date) DESC;

