-- ============================================================
-- Korakuen Management System — Seed Data
-- Migration: 005 (combined from supabase/seeds/)
-- Date: 2026-03-01
-- Tags, partner companies, bank accounts
--
-- SOURCE OF TRUTH: supabase/seeds/001_tags.sql,
--   002_partner_companies.sql, 003_bank_accounts.sql
-- This migration was generated by combining those files.
-- To update seed data, edit the source files in supabase/seeds/
-- and regenerate this migration.
-- ============================================================

-- ============================================================
-- Korakuen Management System — Seed Data: Tags
-- File: 001_tags.sql
-- Date: 2026-03-01
--
-- Seeds the tags table with the 25 master tags from the schema
-- document (docs/08_schema.md, "Tags — Master List (Updated)").
--
-- Tags are the universal classification system — used for both
-- entity categorization and project roles. UUIDs auto-generate.
-- ============================================================

-- === Materials Suppliers ===

INSERT INTO tags (name, notes) VALUES
  ('concrete_supplier', 'Supplier of concrete and ready-mix products'),
  ('metal_supplier', 'Supplier of metal products — rebar, steel sheets, structural steel'),
  ('wood_supplier', 'Supplier of wood and lumber for construction'),
  ('aggregates_supplier', 'Supplier of sand, gravel, and crushed stone'),
  ('cement_supplier', 'Supplier of cement and related binding materials'),
  ('brick_supplier', 'Supplier of bricks, blocks, and masonry units'),
  ('paint_supplier', 'Supplier of paint, coatings, and finishing materials'),
  ('electrical_materials_supplier', 'Supplier of electrical materials — cables, conduits, panels'),
  ('plumbing_materials_supplier', 'Supplier of plumbing materials — pipes, fittings, fixtures'),
  ('general_materials_supplier', 'Supplier of miscellaneous construction materials not covered by other tags');

-- === Subcontractors by Trade ===

INSERT INTO tags (name, notes) VALUES
  ('electrical_subcontractor', 'Subcontractor specializing in electrical installations'),
  ('plumbing_subcontractor', 'Subcontractor specializing in plumbing and sanitary installations'),
  ('civil_works_subcontractor', 'Subcontractor for general civil works — foundations, structures, finishing'),
  ('carpentry_subcontractor', 'Subcontractor specializing in carpentry and woodwork'),
  ('steel_works_subcontractor', 'Subcontractor specializing in steel fabrication and installation');

-- === Equipment ===

INSERT INTO tags (name, notes) VALUES
  ('equipment_rental', 'Equipment rental provider — machinery, tools, scaffolding'),
  ('transport_logistics', 'Transport and logistics services — material delivery, freight');

-- === Services ===

INSERT INTO tags (name, notes) VALUES
  ('legal_services', 'Legal advisory and documentation services'),
  ('accounting_services', 'Accounting, bookkeeping, and tax advisory services'),
  ('engineering_services', 'Engineering consulting and design services'),
  ('topography_services', 'Topographic surveying and land measurement services');

-- === Other ===

INSERT INTO tags (name, notes) VALUES
  ('government_supervisor', 'Government entity or official supervising project execution'),
  ('oxi_financing_company', 'Private company financing public works under the OxI (Obras por Impuesto) framework'),
  ('client', 'Client entity — the party contracting Korakuen for project execution'),
  ('general_supplier', 'General-purpose supplier not fitting a specific material or trade category');


-- ============================================================
-- Korakuen Management System — Seed Data: Partner Companies
-- File: 002_partner_companies.sql
-- Date: 2026-03-01
--
-- Seeds the partner_companies table with 3 partner companies.
--
-- *** ALL VALUES ARE PLACEHOLDERS ***
-- Replace names, RUCs, document numbers, and contact info
-- with real data before running in production.
--
-- Partner 1 (Alex): bank_tracking_full = true (full bank tracking)
-- Partners 2 & 3: bank_tracking_full = false (reference only)
-- ============================================================

-- Partner 1 — Alex (full bank tracking)
-- PLACEHOLDER: Replace name, ruc, owner details with real data
INSERT INTO partner_companies (name, ruc, owner_name, owner_document_type, owner_document_number, bank_tracking_full)
VALUES (
  'Korakuen SAC',       -- PLACEHOLDER: real company name
  '20000000001',        -- PLACEHOLDER: real 11-digit RUC
  'Alex Partner',       -- PLACEHOLDER: real owner full name
  'DNI',
  '00000001',           -- PLACEHOLDER: real 8-digit DNI
  true                  -- Alex gets full bank balance tracking
);

-- Partner 2
-- PLACEHOLDER: Replace name, ruc, owner details with real data
INSERT INTO partner_companies (name, ruc, owner_name, owner_document_type, owner_document_number, bank_tracking_full)
VALUES (
  'Partner B SAC',      -- PLACEHOLDER: real company name
  '20000000002',        -- PLACEHOLDER: real 11-digit RUC
  'Partner B',          -- PLACEHOLDER: real owner full name
  'DNI',
  '00000002',           -- PLACEHOLDER: real 8-digit DNI
  false                 -- reference only — no full bank tracking
);

-- Partner 3
-- PLACEHOLDER: Replace name, ruc, owner details with real data
INSERT INTO partner_companies (name, ruc, owner_name, owner_document_type, owner_document_number, bank_tracking_full)
VALUES (
  'Partner C SAC',      -- PLACEHOLDER: real company name
  '20000000003',        -- PLACEHOLDER: real 11-digit RUC
  'Partner C',          -- PLACEHOLDER: real owner full name
  'DNI',
  '00000003',           -- PLACEHOLDER: real 8-digit DNI
  false                 -- reference only — no full bank tracking
);


-- ============================================================
-- Korakuen Management System — Seed Data: Bank Accounts
-- File: 003_bank_accounts.sql
-- Date: 2026-03-01
--
-- Seeds bank accounts for all three partner companies.
-- Uses subqueries on RUC to reference partner_companies by ID
-- since UUIDs are auto-generated.
--
-- *** ALL last4 DIGITS ARE PLACEHOLDERS ***
-- Replace with real last-4 account digits before production.
--
-- Alex (Korakuen SAC): 4 accounts (full bank tracking)
--   - BCP PEN checking
--   - Interbank PEN checking
--   - BCP USD checking
--   - Banco de la Nacion PEN detraccion
--
-- Partner B: 1 account (reference only)
--   - BCP PEN checking
--
-- Partner C: 1 account (reference only)
--   - BBVA PEN checking
-- ============================================================

-- === Alex (Korakuen SAC) — Full bank tracking ===

-- BCP PEN checking account
-- PLACEHOLDER: last4 '0001' — replace with real last 4 digits
INSERT INTO bank_accounts (partner_company_id, bank_name, account_number_last4, account_type, currency, is_detraccion_account)
VALUES (
  (SELECT id FROM partner_companies WHERE ruc = '20000000001'),
  'BCP',
  '0001',               -- PLACEHOLDER: real last 4 digits
  'checking',
  'PEN',
  false
);

-- Interbank PEN checking account
-- PLACEHOLDER: last4 '0002' — replace with real last 4 digits
INSERT INTO bank_accounts (partner_company_id, bank_name, account_number_last4, account_type, currency, is_detraccion_account)
VALUES (
  (SELECT id FROM partner_companies WHERE ruc = '20000000001'),
  'Interbank',
  '0002',               -- PLACEHOLDER: real last 4 digits
  'checking',
  'PEN',
  false
);

-- BCP USD checking account
-- PLACEHOLDER: last4 '0003' — replace with real last 4 digits
INSERT INTO bank_accounts (partner_company_id, bank_name, account_number_last4, account_type, currency, is_detraccion_account)
VALUES (
  (SELECT id FROM partner_companies WHERE ruc = '20000000001'),
  'BCP',
  '0003',               -- PLACEHOLDER: real last 4 digits
  'checking',
  'USD',
  false
);

-- Banco de la Nacion PEN detraccion account
-- PLACEHOLDER: last4 '0004' — replace with real last 4 digits
INSERT INTO bank_accounts (partner_company_id, bank_name, account_number_last4, account_type, currency, is_detraccion_account)
VALUES (
  (SELECT id FROM partner_companies WHERE ruc = '20000000001'),
  'Banco de la Nación',
  '0004',               -- PLACEHOLDER: real last 4 digits
  'detraccion',
  'PEN',
  true                   -- this IS the detraccion account
);

-- === Partner B — Reference only ===

-- BCP PEN checking account
-- PLACEHOLDER: last4 '0005' — replace with real last 4 digits
INSERT INTO bank_accounts (partner_company_id, bank_name, account_number_last4, account_type, currency, is_detraccion_account)
VALUES (
  (SELECT id FROM partner_companies WHERE ruc = '20000000002'),
  'BCP',
  '0005',               -- PLACEHOLDER: real last 4 digits
  'checking',
  'PEN',
  false
);

-- === Partner C — Reference only ===

-- BBVA PEN checking account
-- PLACEHOLDER: last4 '0006' — replace with real last 4 digits
INSERT INTO bank_accounts (partner_company_id, bank_name, account_number_last4, account_type, currency, is_detraccion_account)
VALUES (
  (SELECT id FROM partner_companies WHERE ruc = '20000000003'),
  'BBVA',
  '0006',               -- PLACEHOLDER: real last 4 digits
  'checking',
  'PEN',
  false
);

